<!DOCTYPE html>
<html lang="pt-BR">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Mirabel / Consumer Lab</title>
<style>
:root{--ink:#17212b;--paper:#edf2f3;--card:#fff;--blue:#176b87;--green:#31745c;--red:#d85d4c;--line:#cad8dc;--muted:#68777d}*{box-sizing:border-box}body{margin:0;background:linear-gradient(135deg,#edf2f3,#f8eee7);color:var(--ink);font-family:Arial,sans-serif}main{width:min(1080px,calc(100% - 40px));margin:auto;padding:28px 0 70px}nav{display:flex;justify-content:space-between;font-size:13px;font-weight:700}nav a{color:var(--blue);text-decoration:none}header{margin:65px 0 32px;max-width:750px}.eyebrow{color:var(--red);font-size:12px;font-weight:800;letter-spacing:.14em;text-transform:uppercase}h1{margin:10px 0;font:400 clamp(2.8rem,7vw,6rem)/.9 Georgia,serif;letter-spacing:-.06em}.intro{color:var(--muted);font-size:16px;line-height:1.6}.layout{display:grid;grid-template-columns:320px 1fr;gap:20px;align-items:start}section{border:1px solid var(--line);background:rgba(255,255,255,.9);padding:24px;box-shadow:8px 8px 0 rgba(23,107,135,.08)}label{display:block;margin:17px 0 6px;color:var(--muted);font-size:11px;font-weight:800;letter-spacing:.08em;text-transform:uppercase}input{width:100%;padding:13px;border:1px solid #afc0c5;font:20px Georgia,serif}button{width:100%;margin-top:22px;padding:15px;border:0;background:var(--red);color:#fff;cursor:pointer;font-weight:800;text-transform:uppercase}.run-title{display:flex;justify-content:space-between;align-items:center}h2{margin:0;font:400 28px Georgia,serif}.state{color:var(--blue);font-weight:800;text-transform:uppercase}progress{width:100%;height:18px;margin:22px 0;accent-color:var(--blue)}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.stat{padding:15px;border-top:3px solid var(--blue);background:#f5f9fa}.stat span{display:block;color:var(--muted);font-size:10px;font-weight:800;text-transform:uppercase}.stat strong{display:block;margin-top:7px;color:var(--blue);font:400 28px Georgia,serif}.explain{margin-top:20px;padding:15px;background:#edf7f1;color:var(--green);font-size:14px;line-height:1.5}.note{color:var(--muted);font-size:12px;line-height:1.5}@media(max-width:760px){main{width:min(100% - 24px,600px)}.layout{display:block}.layout section+section{margin-top:18px}.stats{grid-template-columns:repeat(2,1fr)}}
</style>
</head>
<body><main>
@include('partials.lab-navigation')
<header><div class="eyebrow">Mirabel / Consumer verification</div><h1>Publique. Consuma. Meça.</h1><p class="intro">Este teste coloca mensagens reais na fila e inicia consumers reais. O resultado mostra se o consumo acompanha a entrada ou se o backlog começa a crescer.</p></header>
@if ($errors->has('consumers'))<p class="explain" role="alert">{{ $errors->first('consumers') }}</p>@endif
<div class="layout"><section><h2>Cenário</h2><form method="POST" action="{{ url('/consumer-lab/start') }}">@csrf<label for="messages">Mensagens</label><input id="messages" name="messages" type="number" min="1" max="100000" value="1000" required><label for="consumers">Consumers</label><input id="consumers" name="consumers" type="number" min="1" max="8" value="1" required><p class="note">Cada consumer é um worker real conectado ao RabbitMQ. O máximo protegido é 8.</p><button type="submit">Iniciar teste</button></form></section>
<section><div class="run-title"><h2>Fila em tempo real</h2><span class="state" id="state">{{ session('consumer_run_id') ? 'queued' : 'idle' }}</span></div><progress id="progress" max="1" value="0"></progress><div class="stats"><div class="stat"><span>Publicadas</span><strong id="published">0</strong></div><div class="stat"><span>Processadas</span><strong id="processed">0</strong></div><div class="stat"><span>Backlog</span><strong id="backlog">0</strong></div><div class="stat"><span>Consumers</span><strong id="consumers">0</strong></div><div class="stat"><span>Tempo</span><strong id="elapsed">0s</strong></div><div class="stat"><span>Diferença</span><strong id="difference">0</strong></div></div><div class="explain" id="explain">Inicie um teste para acompanhar a fila e o processamento real.</div></section></div>
@if (!empty($history))
<section style="margin-top:20px;overflow:auto"><h2>Histórico de consumos</h2><p class="note">Execuções com totais diferentes são incompletas; a vazão só considera mensagens processadas e contabilizadas.</p><table style="width:100%;border-collapse:collapse;font-size:13px"><thead><tr><th style="text-align:left;padding:10px;border-bottom:1px solid var(--line)">Encerrado em</th><th style="text-align:left;padding:10px;border-bottom:1px solid var(--line)">Situação</th><th style="text-align:left;padding:10px;border-bottom:1px solid var(--line)">Mensagens</th><th style="text-align:left;padding:10px;border-bottom:1px solid var(--line)">Processadas</th><th style="text-align:left;padding:10px;border-bottom:1px solid var(--line)">Diferença</th><th style="text-align:left;padding:10px;border-bottom:1px solid var(--line)">Configurados / ativos</th><th style="text-align:left;padding:10px;border-bottom:1px solid var(--line)">Tempo até zerar</th><th style="text-align:left;padding:10px;border-bottom:1px solid var(--line)">Vazão (msg/s)</th><th style="text-align:left;padding:10px;border-bottom:1px solid var(--line)">Backlog final</th></tr></thead><tbody>@foreach ($history as $run)<tr><td style="padding:10px;border-bottom:1px solid var(--line)">{{ isset($run['completed_at']) ? \Illuminate\Support\Carbon::parse($run['completed_at'])->format('d/m/Y H:i') : '-' }}</td><td style="padding:10px;border-bottom:1px solid var(--line)">{{ (($run['status'] ?? null) === 'incomplete' || (int) ($run['processed'] ?? 0) !== (int) ($run['published'] ?? 0)) ? 'Incompleto' : 'Concluído' }}</td><td style="padding:10px;border-bottom:1px solid var(--line)">{{ number_format($run['published'] ?? 0, 0, ',', '.') }}</td><td style="padding:10px;border-bottom:1px solid var(--line)">{{ number_format($run['processed'] ?? 0, 0, ',', '.') }}</td><td style="padding:10px;border-bottom:1px solid var(--line)">{{ number_format(abs((int) ($run['published'] ?? 0) - (int) ($run['processed'] ?? 0)), 0, ',', '.') }}</td><td style="padding:10px;border-bottom:1px solid var(--line)">{{ $run['requested_consumers'] ?? '-' }} / {{ $run['consumers'] ?? 0 }}</td><td style="padding:10px;border-bottom:1px solid var(--line)">{{ number_format(($run['consumer_elapsed_ms'] ?? $run['elapsed_ms'] ?? 0) / 1000, 2, ',', '.') }}s</td><td style="padding:10px;border-bottom:1px solid var(--line)">{{ (int) ($run['processed'] ?? 0) === (int) ($run['published'] ?? 0) ? number_format($run['throughput'] ?? 0, 2, ',', '.') : '-' }}</td><td style="padding:10px;border-bottom:1px solid var(--line)">{{ $run['backlog'] ?? 0 }}</td></tr>@endforeach</tbody></table></section>
@endif
</main>
@if(session('consumer_run_id'))<script>(function(){const runId=@json(session('consumer_run_id'));const url=@json(url('/consumer-lab/status'))+'?run_id='+encodeURIComponent(runId);const set=(id,value)=>document.getElementById(id).textContent=value;const poll=()=>fetch(url,{headers:{Accept:'application/json'}}).then(r=>r.json()).then(run=>{const published=Number(run.published||0),processed=Number(run.processed||0),backlog=Number(run.backlog||0),difference=published-processed;set('state',run.status==='completed'?'finalizado':run.status==='incomplete'?'incompleto':run.status);set('published',published.toLocaleString('pt-BR'));set('processed',processed.toLocaleString('pt-BR'));set('backlog',backlog.toLocaleString('pt-BR'));set('consumers',Number(run.consumers||0).toLocaleString('pt-BR'));set('elapsed',((run.elapsed_ms||0)/1000).toFixed(2).replace('.',',')+'s');set('difference',Math.abs(difference).toLocaleString('pt-BR'));document.getElementById('progress').max=Math.max(1,published);document.getElementById('progress').value=processed;set('explain',run.status==='completed'?'Todos os eventos publicados foram processados. A fila está saudável.':run.status==='incomplete'?'Divergência: '+Math.abs(difference).toLocaleString('pt-BR')+' mensagens não conferem entre publicação e processamento.':backlog>0?'A fila ainda possui '+backlog.toLocaleString('pt-BR')+' mensagens aguardando consumo.':'Aguardando o publisher e os consumers iniciarem.');if((run.status!=='completed'&&run.status!=='incomplete')||backlog>0)window.setTimeout(poll,700)}).catch(()=>window.setTimeout(poll,1200));poll()}())</script>@endif
</body></html>
